inherit_gem:
  groundwork-style:
    - rubocop.yml
    - rubocop_performance.yml
    - rubocop_rails.yml
    - rubocop_rake.yml
    - rubocop_rspec.yml

# RSpec macro style is generally parentheses-less.
Style/MethodCallWithArgsParentheses:
  Enabled: false

